name: Release
on:
  # 合并后自动发布
  # push:
  #   branches: [ master, main, next, beta, "*.x" ]

  # 手动发布
  workflow_dispatch:

jobs:
  release:
    name: Node.js
    uses: artusjs/github-actions/.github/workflows/node-release.yml@master
    # with:
      # checkTest: false
      # dryRun: true
